server:
  port: ${PARAM_SERVER_PORT:1001}
  servlet:
    context-path: /easy-learning
management:
  server:
    port: ${PARAM_MANAGEMENT_SERVER_PORT:1001}
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,prometheus
      path-mapping:
        health: /actuator/health
        prometheus: /prometheus/metrics

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  # Config mail
  mail:
    host: ${EMAIL.HOST:smtp.gmail.com}
    port: ${EMAIL.PORT:587}
    username: ${EMAIL.USERNAME:kiet@example.com}
    password: ${EMAIL.PASSWORD:cfoarjgkprvmvgvx}
    properties:
      mail:
        smtp:
          auth: ${EMAIL.AUTH:true}
          starttls:
            enable: ${EMAIL.ENABLE:true}
  datasource:
    url: jdbc:mysql://${MYSQL.HOST:localhost}:3306/${MYSQL.DATABASE:temp_db}?useSSL=false&serverTimezone=UTC
    username: ${MYSQL.USERNAME:root}
    password: ${MYSQL.PASSWORD:password}

    hikari:
      connectionTimeout: ${DATASOURCE.CONNECTION.TIMEOUT:30000}
      idleTimeout: ${DATASOURCE.IDLE.TIMEOUT:600000}
      maxLifetime: ${DATASOURCE.MAX_LIFE_TIME:0}
      minimum-idle: ${DATASOURCE.MINIMUM_IDLE:5}
      maximum-pool-size: ${DATASOURCE.MAXIMUM_POOL_SIZE:50}
  jpa:
    show-sql: ${JPA.SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: ${FORMAT_SQL:true}
        use_nationalized_character_data: true
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    ssl: ${REDIS_SSL:false}
    password: ${REDIS_PASSWORD:""}
    database: ${REDIS_DATABASE:0}
internal-url:
  configuration-service:

SECRET:
  KEY: ${SECRET.KEY:6KGMeQrk6AGC6xJMBeqWwkY/udp6ALKljw5RTHevYlhutlKMrG4/qnIsaq5G46BJ}

redis:
  host: localhost
  port: 6379

#Cloudinary config
cloudinary:
  cloud_name: dfz7841n3
  api_key: 983357693662753
  api_secret: TY2Wz3vGIBKnvqcTUXkdmiwvSFY

#App config
app:
  config:
    domain: "http://localhost:1001/easy-learning"
    path:
      valid_token: "/public/v1/user/valid-token?token="
